// <auto-generated />
using System;
using DES_COGNITIVO_FUN_PROG.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DES_COGNITIVO_FUN_PROG.Migrations
{
    [DbContext(typeof(GestionEventosContext))]
    partial class GestionEventosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Administrador", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAdmin");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_identidad");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.EstadoEvento", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("EstadoEvento1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EstadoEvento");

                    b.HasKey("IdEstado");

                    b.ToTable("Estado_Evento", (string)null);
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("CodigoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdEvento");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Invitado", b =>
                {
                    b.Property<int>("IdInvitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInvitado"));

                    b.Property<bool?>("Confirmado")
                        .HasColumnType("bit");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DNI");

                    b.Property<DateOnly?>("FechaConfirmacion")
                        .HasColumnType("date");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("NumAcompañantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdInvitado");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdMesa");

                    b.ToTable("Invitado", (string)null);
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.HasKey("IdMesa");

                    b.HasIndex("IdEvento");

                    b.ToTable("Mesa", (string)null);
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Evento", b =>
                {
                    b.HasOne("DES_COGNITIVO_FUN_PROG.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Eventos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Evento_Cliente");

                    b.HasOne("DES_COGNITIVO_FUN_PROG.Models.EstadoEvento", "IdEstadoNavigation")
                        .WithMany("Eventos")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Evento_Estado");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Invitado", b =>
                {
                    b.HasOne("DES_COGNITIVO_FUN_PROG.Models.Evento", "IdEventoNavigation")
                        .WithMany("Invitados")
                        .HasForeignKey("IdEvento")
                        .IsRequired()
                        .HasConstraintName("FK_Invitado_Evento");

                    b.HasOne("DES_COGNITIVO_FUN_PROG.Models.Mesa", "IdMesaNavigation")
                        .WithMany("Invitados")
                        .HasForeignKey("IdMesa")
                        .HasConstraintName("FK_Invitado_Mesa");

                    b.Navigation("IdEventoNavigation");

                    b.Navigation("IdMesaNavigation");
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Mesa", b =>
                {
                    b.HasOne("DES_COGNITIVO_FUN_PROG.Models.Evento", "IdEventoNavigation")
                        .WithMany("Mesas")
                        .HasForeignKey("IdEvento")
                        .IsRequired()
                        .HasConstraintName("FK_Mesa_Evento");

                    b.Navigation("IdEventoNavigation");
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Cliente", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.EstadoEvento", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Evento", b =>
                {
                    b.Navigation("Invitados");

                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("DES_COGNITIVO_FUN_PROG.Models.Mesa", b =>
                {
                    b.Navigation("Invitados");
                });
#pragma warning restore 612, 618
        }
    }
}
